alias vd="vagrant destroy -f"
alias vs="vagrant status"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vp="vagrant provision"
alias vrp="vagrant reload --provision"
alias vsr="vagrant sandbox rollback"
